### ISSUE TITLE
Plans for a non-ERCF version?

### ISSUE THREAD

**Issue by KoeRt888** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#10]
Hi,
I know you had a version without the ERCF sensor before. 
Just wondering if you plan on releasing a non-ERCF version again? 
If not could the current files be used without the ERCF sensor?

**Comment by salbang** [comment]
> Hi,
> 
> I know you had a version without the ERCF sensor before. 
> 
> Just wondering if you plan on releasing a non-ERCF version again? 
> 
> If not could the current files be used without the ERCF sensor?

IMHO, you can just use ercf version without having the sensor with no problem.

**Comment by Eytecz** [comment]
> Hi, I know you had a version without the ERCF sensor before. Just wondering if you plan on releasing a non-ERCF version again? If not could the current files be used without the ERCF sensor?

Hi, yes I had one before. At the moment right now I do not have plans to make a non-ercf version as the ercf version can be used without the sensor.
