### ISSUE TITLE
Need more motor clearance on Rear_Body

### ISSUE THREAD

**Issue by x4runnerGunnerx** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#11]
<img width="323" alt="Capture" src="https://user-images.githubusercontent.com/74921101/192617405-00893aad-47e0-447d-90e6-13dbddfd5607.PNG">

I think this radius around the motor needs another 1mm or so of clearance as it is rubbing on the motor and on the LGX lite body on the top causing it to flex out of shape slightly.

**Comment by x4runnerGunnerx** [comment]
![IMG_2871 (1)](https://user-images.githubusercontent.com/74921101/192619976-da0c13ed-bad3-4abf-8c0a-bc8210df22ba.JPG)

**Comment by Eytecz** [comment]
Are there more cases with this issue? Haven't heard about it before. There is clearance in the CAD, which is based on the original LGX Lite CAD from Bondtech. If the issue persists for more people I"ll look into it.
