### ISSUE TITLE
Not an Issue, but a question. 

### ISSUE THREAD

**Issue by 32368734** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#15]
Do you think this is going to work with a SB2040 pcb?

**Comment by BigBadLoser** [comment]
It doesn't work with CAN boards

**Comment by 32368734** [comment]
Thanks for you answer. Do you know if there are other options for stealthburner in combination with lgx lite and canbus?

**Comment by BigBadLoser** [comment]
There are toolheads that fit EBB36, I know bondtechs new official LGX Lite mount works for EBB36. I hope someone figures out a solution for sb2040 and sb2240 soon, would love to use them with my LGX Lite.
