### ISSUE TITLE
UM2

### ISSUE THREAD

**Issue by rlaferla** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#3]
I cannot find these UM2 collets.  The ones on AliExpress are on a 2 month backorder.  Is there a way to redesign the part to use something more available?  Perhaps even the original LGX Lite one?  I have also tried two different types which involved shipping costs that were a multiple of the product.  It's not that I am not trying...

**Comment by SvenBarracuda** [comment]
any chance to get a photo too see where all the brass m3 heatinserts goes? only can imagine 4 of your pics...dont want to rip apart my working SB on CW1 just to see that i missed something

**Comment by rlaferla** [comment]
I filed an issue on the heat inserts and screws but it was closed.  We really need a diagram or photo like you said.

**Comment by rlaferla** [comment]
I know believe this is a bug in the non-ECRF model.  The ECRF model has a hole for that fits the UM2 collet perfectly.  The non-ECRF version does not.  Please fix this.

**Comment by Jaans** [comment]
Here are some photos of my assembly showing where I placed inserts (or at least where I think they should go):
![LGX Lite mount plate inside](https://user-images.githubusercontent.com/3510981/171805069-891ba35a-366d-47cc-b08d-bb57c6baa2f7.jpg)
![LGX Lite mount plate outside](https://user-images.githubusercontent.com/3510981/171805081-80625677-f925-47da-9902-b452a2bf9964.jpg)

Remember the side insert for closing the wire cover door.
![LGX Lite mount plate outside with angle](https://user-images.githubusercontent.com/3510981/171805099-dba68e3a-9e32-4bff-aae9-766585772730.jpg)

Once assembled with motor:
![LGX Lite mount assembled - front](https://user-images.githubusercontent.com/3510981/171805123-11a392a4-35f4-487a-af97-a61dad89e768.jpg)
![LGX Lite mount assembled - rear](https://user-images.githubusercontent.com/3510981/171805137-280d3e0f-1275-4668-8b53-6eb48b675592.jpg)

**Comment by Eytecz** [comment]
New design has been made, if more people have this issue a modification can be made.
