### ISSUE TITLE
ERCF sensor triggering due to bolts

### ISSUE THREAD

**Issue by funkyskull** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#4]
This is a great design, but I ran into issues with the bolts on either side of the magnet. 
When completely assembled the ERCF magnetic was constantly triggered. 
After a bit of trouble-shooting I found that removing the two bolts resolved the issue.
Maybe consider removing those bolt holes or specing aluminum bolts, which might remove the effect?

 btw - I redesigned the front plate to use an ECAS fitting and it works great. Again thanks for the great design.

**Comment by mattapperson** [comment]
Nice @funkyskull i was pulling my hair out having tested this pre-release and it worked and then ran into the always triggered issue post-release. Tried your suggestion and it seems to have fixed it! Must have failed to install those screws during testing 🤦‍♂️

**Comment by mattapperson** [comment]
@funkyskull would you mind sharing your version?

**Comment by Eytecz** [comment]
New design has been uploaded where this issue has been resolved.
