### ISSUE TITLE
Extruder filament hole is slightly offset to the right

### ISSUE THREAD

**Issue by damiandudycz** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#5]
I don't know if it's due to some changes in the original parts design, but for some reason the extruder I slightly too far to the right (looking from the front). Would it be possible to adjust it to the newest parts?

**Comment by ctilley83** [comment]
> I don't know if it's due to some changes in the original parts design, but for some reason the extruder I slightly too far to the right (looking from the front). Would it be possible to adjust it to the newest parts?

Were you able to fix this issue on your own? I'm worried about this myself.

**Comment by jeronbernal** [comment]
please keep us updated

**Comment by Jaans** [comment]
FWIW, I printed a new set of CW2 and LGX Lite and it aligns perfectly. Not sure why yours is offset? How much is it - do you have a photo?

I did notice that the little square nuts of the LGX Lite has some movement in them to adjust, so maybe it's that ?

**Comment by damiandudycz** [comment]
After measuring it in Fusion 360 - it was 0.2mm, nearly visible. But still. FYI - this issue was also present in original Stelathburner files, so I guess this is why it was moved here as well. I know 0.2mm is not a real issue, but just mentioning - it is there.

**Comment by Jaans** [comment]
@damiandudycz Cool - good to know, and by how much

**Comment by jvandervyver** [comment]
wile.e did get question about it in the Voron discord and said it should be a non-issue.  Next day he ended up fixing it and when I asked some time later, he said it would be fixed in the final release of SB/CW2.  So no beta update for that problem

**Comment by Eytecz** [comment]
New design has been uploaded where this issue has been resolved. However in the original Voron design this issue is still present.
