### ISSUE TITLE
Please make Fusion 360 .f3d model available

### ISSUE THREAD

**Issue by Jaans** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#6]
This design is fantastic and has so much promise!
Thank you for sharing.

Would you be open to sharing the source CAD model, assuming it's a Fusion 360 .f3d model? 
(The STEP files lack parametric history)

That would open it up to others to adapt it to the minor issues reported like:
- UM2 collet fitting only the sensor version 
- ECAS fitting support (and other?)
- Potential alignment issue with filament hole
- Hall Effect Sensor issue with spaced bolts

Thanks again for this!

**Comment by Eytecz** [comment]
I have made the STEP files available. The base design is not made in Fusion 360 but in Solid Edge, which means I can't make the f3d model available as it does not exist.

**Comment by Jaans** [comment]
Awesome and thank you for doing this mod in the first place.
