### ISSUE TITLE
Ercf Sensor not working

### ISSUE THREAD

**Issue by 33martin** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#7]
has anyone managed to get the sensor to work?  my sensor switches perfectly outside the housing.  when i put it in it doesn't work (and yes the washer is magnetic)

**Comment by 33martin** [comment]
fixed my problem by using 2 magnets in a row.  I'll try modifying the cad file to put the magnet deeper into the case

**Comment by Benoitone** [comment]
Your magnet may not be powerful enough. Maybe it's better that you find a more powerful magnet... If you modify to have the magnet closer to the washer you may have the opposite problem...

**Comment by 33martin** [comment]
I have tried various really strong neodyn magnets (the washer was also pulled strongly towards the magnet) but without success.  only when I used the second magnet it worked without any problems

**Comment by Benoitone** [comment]
Do you really use AH3364Q-P-B hall sensor?

**Comment by eamars** [comment]
I realized the hall effect sensor shouldn't be pushed all the way in otherwise it won't sense the change to the washer position. I suggest you to tune the position of the sensor first to see if that helps.

**Comment by Jo3yDaPh1sH** [comment]
Stacking a second magnet worked for me.

**Comment by Eytecz** [comment]
New design has been uploaded where this issue has been resolved. The fix was to remove the bolt on the sensor side going from the front to the back piece.
