### ISSUE TITLE
Suggested Improvement, PTFE Tube 1 piece

### ISSUE THREAD

**Issue by lococnc** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#8]
Let the PTFE tube from the toolhead pass all the way up into the bottom receiver on the LGX Lite. I drilled it out to 4mm and this also ensures alignment of the filament path.
![image](https://user-images.githubusercontent.com/46273940/179530123-c34efa3b-f4ac-4bff-b04d-dd31b67108e4.png)

**Comment by Eytecz** [comment]
Good modification, but is not relevant for the ERCF version, which is the only version I made available until now with the new design.
