### ISSUE TITLE
Adapt to released CW2 

### ISSUE THREAD

**Issue by KoeRt888** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#9]
Hi,
Is it possible for you to adjust the LGX Lite mount to the new CW2 specific hotend mounts? 
With Stealthburner's release the CAD files are available [here](https://github.com/VoronDesign/Voron-Stealthburner)

**Comment by dmnkhhn** [comment]
Did you identify any specific parts that need adjustments? I'm about to build the Stealthburner with the LGX Lite extruder and the Rapido hotend and a quick moving around of the parts in Fusion 360 (see attached file) it all looks quite good actually.
<img width="573" alt="Bildschirmfoto 2022-07-30 um 12 50 54" src="https://user-images.githubusercontent.com/229676/181907662-79af8025-877a-4c08-b3f5-c005a101432f.png">

**Comment by KoeRt888** [comment]
It all lines up well except for the gap between the toolhead an the front extruder plate. There is a 1mm gap where CW2 doesn't have one. 
![SBrel_LGXLite](https://user-images.githubusercontent.com/65965320/182168979-cd789999-d9ad-48fa-a813-d53643fbe977.png)

Cosmetically the toolhead has a new shape here but that isn't a big deal in my eyes:
![SBrel_LGXLite_cosmetic](https://user-images.githubusercontent.com/65965320/182169362-d28abd89-f7d2-4ca3-a385-fad44babf917.png)

**Comment by Eytecz** [comment]
New design has been uploaded where this issue has been resolved.
